### ISSUE TITLE
Assertion bug in utilities.py

### ISSUE THREAD

**Issue by vasbala** [google/cluster-insight#20]
The assertion in utilities.py:215 may not be true in all Kubernetes deployments. It can be safely removed:

     assert len(elements) == 4

**Comment by EranGabber** [comment]
Did this assertion caused a run-time failure?
If it did, what was the input that caused it to fail?

_node_id_helper() assumes that the input node_id has a certain structure (for example, exactly four period-separated fields). Otherwise it cannot be used to extract the host name and the project name safely from node_id. This helper function is called from node_id_to_project_name() and node_id_to_host_name(). Without this assertion, the results from the latter two functions cannot be trusted.

**Comment by EranGabber** [comment]
I found an example node ID with more than 4 dot-separated components:
kubernetes-minion-dlc9.c.spartan-alcove-89517.google.com.internal

The general format of the node ID is:
<host name>.c.<project name>.internal
The <project name> may contain internal periods.

The solution for this bug is not to remove the assert, but to parse the node ID correctly.

**Comment by vasbala** [comment]
Agree. But I thought your assertion was about the number of "." separated
segments in the string, which is not reliable.

Separately, we should test this on many more Kubenernetes apps, including
those installed on platforms other than GKE.
